import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { TestDefinition } from '../../types';

export class TestRecorder {
  constructor() {}

  async start(): Promise<void> {
    console.log('\n📝 Interactive Test Recorder (TypeScript)\n');
    const answers = await inquirer.prompt([
      { name: 'id', message: 'Test ID:', validate: v => !!v },
      { name: 'name', message: 'Test Name:', validate: v => !!v },
      { name: 'description', message: 'Description:', validate: v => !!v },
      { name: 'priority', message: 'Priority (High/Medium/Low):', default: 'Medium' },
      { name: 'tags', message: 'Tags (comma separated):', filter: (v: string) => v.split(',').map(t => t.trim()) },
      { name: 'site', message: 'Target site URL:', validate: v => !!v },
      { name: 'task', message: 'Describe the test scenario in plain English:', validate: v => !!v }
    ]);
    const test: TestDefinition = {
      ...answers,
      priority: answers.priority || 'Medium',
      tags: answers.tags || [],
      testData: {},
    };
    const fileName = `${answers.id.replace(/[^a-zA-Z0-9_-]/g, '_')}.ts`;
    const filePath = path.join(process.cwd(), 'src', 'tests', fileName);
    const fileContent = `// Auto-generated by TestRecorder\nexport const ${answers.id.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()} = ${JSON.stringify(test, null, 2)};\n`;
    await fs.writeFile(filePath, fileContent, 'utf8');
    console.log(`\n✅ Test saved to src/tests/${fileName}`);
  }
} 